#
# Travis Setup
#

# use ubuntu trusty for newer version of nodejs, used for JS testing
dist: trusty

# faster builds on new travis setup not using sudo
# temporary disable, see https://github.com/travis-ci/travis-ci/issues/6842
#sudo: false
sudo: required
group: edge

# build only on master branches
# commented as this prevents people from running builds on their forks:
# https://github.com/yiisoft/yii2/commit/bd87be990fa238c6d5e326d0a171f38d02dc253a
#branches:
#  only:
#    - master
#    - 3.0


#
# Test Matrix
#

language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_TESTS_PHP=1
    - TASK_TESTS_COVERAGE=0
    - TRAVIS_SECOND_USER=travis_two


services:
  - memcached
  - mysql
  - postgresql

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

# try running against postgres 9.6
addons:
  postgresql: "9.6"
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
  code_climate:
    repo_token: 2935307212620b0e2228ab67eadd92c9f5501ddb60549d0d86007a354d56915b

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
      env: TASK_TESTS_COVERAGE=1
    - php: nightly
      services:
        - mysql
        - postgresql

  allow_failures:
    - php: nightly

install:
  - |
    if [[ $TASK_TESTS_COVERAGE != 1 ]]; then
      # disable xdebug for performance reasons when code coverage is not needed
      phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi
  # install composer dependencies
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS

before_script:
  # show some versions and env information
  - php --version
  - composer --version
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      php -r "echo INTL_ICU_VERSION . \"\n\";"
      php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
      psql --version
      mysql --version
    fi
  # initialize databases
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      travis_retry mysql -e 'CREATE DATABASE `yiitest`;';
      mysql -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';";
      mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED WITH mysql_native_password;";
      mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost' WITH GRANT OPTION;";
      psql -U postgres -c 'CREATE DATABASE yiitest;';
    fi
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi
  # Disable DEPRECATE messages during PHPUnit initialization on PHP 7.2. To fix them, PHPUnit should be updated to 6.*
  # For Yii2 tests, messages will be enabled by tests/bootstrap.php
  - |
    if [[ $TRAVIS_PHP_VERSION == 7.2 || $TRAVIS_PHP_VERSION = nightly ]]; then
      echo 'Disabled DEPRECATED notifications for PHP >= 7.2';
      echo 'error_reporting = E_ALL & ~E_DEPRECATED' >> /tmp/php-config.ini;
      phpenv config-add /tmp/php-config.ini;
    fi
script:
  # PHP tests
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --exclude-group wincache,xcache
    fi
after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
notifications:
  slack:
    -
      rooms:
        -
          secure: xX+TazSQB2kgb6mI7/Tz7CfFTgxOC5UJGNT2q5uuQhI/MzaC4bQvBoK42yRsqy5wOz4LihEA3wzSwBRaBeiHlOvasDbOQNMNQF08vLHhVNWK2mCVUsTkrFR2NyaU1VyVl1T9sduN94ED9dl3WTX/nCDm0JVn/62QxnIKQnP70DTuZXe8GamCXsJ0jlXDmRe1ci0s02/HzrJh6MMutmB0xowg5CO9CQ2kqTh/MHpfjx7vSHbHbHFoVbknQlJqXuKxYLpjeov+q7TaFxw6HwnjIIAE3NKPc/NoZxKHZiVIVNnrcHyOCJmVpOUbVWtoUo5cYJ45eg73GaiWvEIBapmp4gb8KInAmffFF+D1AQOy1RsAxOM1N+/neyQp3yigi4KK7EAMTJduXarNRz8lYuRpR4KF4vupScghb1VSQfKcwQhOLTX5mvXVt+AhlqfyeIrjMq1oVovNgPZJEGLNxWHSvZu8BmbEGxkl2KsZvq9A6oe/SykvGibacrpkjgxddM3Y5vsHhxeYVACq/phpePjh6GQBDxKID685tnDD5NyMMduuauf26ZWZ/mI41xa16qONG5HsWbsa/quE+sUimI+eSnR+Q7nO88bQKlC9rNyt0JbuPRcfD8bFjqy/i8iVtXLiVl7qrX/ddm61NctjOcLaZ40L2Nv/+Fe4XMGVkEiiahs=
      on_success: always
      on_failure: never
      on_pull_requests: false
    -
      rooms:
        -
          secure: qzh9xEPfZ4PkhEWLEiCge7TItEYjqV4hvzTtRz3+TUgArZ9UTP2NrIuK/0gyJ2yU8dGQNgrvv1b0gk1nxMjBo1Nfk10p2ZnsuCPQJZfaCPjBc9uPM1jeFeovKCCFme7zbRlhLNzgDihMSR0Uu2Tf0NquOVmdrL/9T+81Kr8xKUXrpC3YQRNVSPmaAZs7VkO4TJLTHREHLqQap6jtORpduMO+zxzVIK54VjCR/Il0cuMxtsYSFpyVfPOvAm4xmAFRGLsLHooQmT494H+VP0aAA+whsy2n+P1khDj3rgE0vU0O1+XFFFxQVsMq3C8x1f89BxSZcopm0Rm6+ZkxV3aAZ47PbVYkZTgNwuHDDINMdecC/1oE+/Vj3u8YGr9zYc1cghXuEQlv4DTkjTXCX74i6aNrC6vpthryp4eH08RweFL5Ur6n7rPxq/9a28aKdAu6QiOtMaqIECiavw9YCtZQCpW4TFoUxiMA2mgmMBwUGSUxt+DGA7AjCXi3C2PbifJmMyy7xEST6Uq3UOGVY2PXsivSTLe7hZpVikczALu/O1rL6WObLoxwuERK++mgdQFEwjb5zSLSO4zuzhRz6OQHnvjgyev+elNPXdRzME0MlbtBqNXe1NaDpLQbOsrk5+IpL/dcSPoq331Deb20vGIeCM9JKcMifykozBteJfGxKtA=
      on_success: never
      on_failure: always
      on_pull_requests: false
